add rust_prepare to Ok requirements

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -970,6 +970,7 @@ jobs:
       - go_examples
       - go_e2e
       - go_integration
+      - rust_prepare
       - rust_lint
       - rust_check
       - turbopack_rust_test
@@ -988,7 +989,7 @@ jobs:
     steps:
       - name: Check cancellation
         id: cancelled
-        if: needs.rust_lint.result == 'cancelled' || needs.rust_check.result == 'cancelled' || needs.turbopack_rust_test.result == 'cancelled' || needs.turborepo_rust_test.result == 'cancelled' || needs.turbopack_rust_test_bench.result == 'cancelled' || needs.rust_build_release.result == 'cancelled' || needs.format_lint.result == 'cancelled' || needs.rust_bench.result == 'cancelled'
+        if: needs.rust_prepare.result == 'cancelled' || needs.rust_lint.result == 'cancelled' || needs.rust_check.result == 'cancelled' || needs.turbopack_rust_test.result == 'cancelled' || needs.turborepo_rust_test.result == 'cancelled' || needs.turbopack_rust_test_bench.result == 'cancelled' || needs.rust_build_release.result == 'cancelled' || needs.format_lint.result == 'cancelled' || needs.rust_bench.result == 'cancelled'
         run: echo "cancelled=true" >> $GITHUB_OUTPUT
 
       - name: Start summary
@@ -1030,6 +1031,12 @@ jobs:
         if: always() && needs.go_e2e.result != 'success' && needs.go_e2e.result != 'skipped'
         run: |
           echo "- Go E2E" >> failures.md
+          exit 1
+
+      - name: Rust Compilation failed
+        if: always() && needs.rust_prepare.result != 'success' && needs.rust_prepare.result != 'skipped'
+        run: |
+          echo "- Rust compilation" >> failures.md
           exit 1
 
       - name: Rust Linting failed
